GitHub action 세팅입니다.
f-lab-edu/message-agent pull request #2
Opened 2023-11-05 10:01 UTC by KTH-96

- java, gradle 세팅

2023-11-08 05:21 UTC, f-lab-lyan commented on .github/workflows/github-action.yml
> +        run: chmod +x ./gradlew
이 줄은 꼭 필요한 것인가요?

2023-11-08 05:22 UTC, f-lab-lyan commented on .github/workflows/github-action.yml
> +          arguments: build
테스트 용이니까, `build`보다는 `test`가 더 좋지 않을까 싶은데요?

2023-11-08 05:22 UTC, f-lab-lyan commented on .github/workflows/github-action.yml
> +    branches: [ "main", "github-action" ]
`"github-action"`이라는 브랜치는 여기에는 필요없지 않을까요?

2023-11-08 07:21 UTC, KTH-96 commented on .github/workflows/github-action.yml
> +    branches: [ "main", "github-action" ]
pr을 날리기 이전에 github action이 성공하는지 확인하고자 적어 놓은 부분인데 지워야 할 거 같습니다.

2023-11-08 07:40 UTC, KTH-96 commented on .github/workflows/github-action.yml
> +        run: chmod +x ./gradlew
밑에 build를 하는 부분에서 gradlew의 실행권한이 없어 빌드가 되지않는 문제가 있어 추가했습니다.

2023-11-08 08:15 UTC, KTH-96 commented on .github/workflows/github-action.yml
> +          arguments: build
test를 사용해도 build.gradle로 프로젝트를 초기화 한다고 하는군요! 수정하겠습니다.
gradle test 명령어를 실행하면 테스트 관련 코드들만 컴파일하고 끝나는 작업이라 생각했습니다.

2023-11-08 13:22 UTC, f-lab-lyan requested changes

2023-11-08 13:22 UTC, f-lab-lyan commented on .github/workflows/github-action.yml
> +        run: chmod +x ./gradlew
https://stackoverflow.com/questions/6476513/git-file-permissions-on-windows

2023-11-15 13:20 UTC, f-lab-lyan approved these changes

2023-11-15 16:52 UTC, merged